export const elements = {
  a: {},
  animate: {},
  animateMotion: {},
  animateTransform: {},
  circle: { attributes: ['cx', 'cy', 'r'] },
  clipPath: {},
  defs: {},
  desc: {},
  discard: {},
  ellipse: {},
  feBlend: {},
  feColorMatrix: {},
  feComponentTransfer: {},
  feComposite: {},
  feConvolveMatrix: {},
  feDiffuseLighting: {},
  feDisplacementMap: {},
  feDistantLight: {},
  feDropShadow: {},
  feFlood: {},
  feFuncA: {},
  feFuncB: {},
  feFuncG: {},
  feFuncR: {},
  feGaussianBlur: {},
  feImage: {},
  feMerge: {},
  feMergeNode: {},
  feMorphology: {},
  feOffset: {},
  fePointLight: {},
  feSpecularLighting: {},
  feSpotLight: {},
  feTile: {},
  feTurbulence: {},
  filter: {},
  foreignObject: {},
  g: {},
  image: {},
  line: {},
  linearGradient: {},
  marker: {},
  mask: {},
  mesh: {},
  meshgradient: {},
  meshpatch: {},
  meshrow: {},
  metadata: {},
  mpath: {},
  path: {},
  pattern: {},
  polygon: {},
  polyline: {},
  radialGradient: {},
  rect: {},
  script: {},
  set: {},
  stop: {},
  style: {},
  svg: {},
  switch: {},
  symbol: {},
  text: {},
  textPath: {},
  title: {},
  tspan: {},
  unknown: {},
  use: {},
  view: {}
}

export const categories = {
  animation: [elements.animate, elements.animateMotion, elements.animateTransform, elements.discard, elements.mpath, elements.set],
  basicShapes: [elements.circle, elements.ellipse, elements.line, elements.polygon, elements.polyline, elements.rect],
  container: [elements.a, elements.defs, elements.g, elements.marker, elements.mask, elements.pattern, elements.svg, elements.switch, elements.symbol, elements.unknown],
  descriptive: [elements.desc, elements.metadata, elements.title],
  filterPrimitive: [elements.feBlend, elements.feColorMatrix, elements.feComponentTransfer, elements.feComposite, elements.feConvolveMatrix, elements.feDiffuseLighting, elements.feDisplacementMap, elements.feDropShadow, elements.feFlood, elements.feFuncA, elements.feFuncB, elements.feFuncG, elements.feFuncR, elements.feGaussianBlur, elements.feImage, elements.feMerge, elements.feMergeNode, elements.feMorphology, elements.feOffset, elements.feSpecularLighting, elements.feTile, elements.feTurbulence],
  gradient: [elements.linearGradient, elements.meshgradient, elements.radialGradient, elements.stop],
  graphic: [elements.circle, elements.ellipse, elements.image, elements.line, elements.mesh, elements.path, elements.polygon, elements.polyline, elements.rect, elements.text, elements.use],
  graphicReferencing: [elements.mesh, elements.use],
  lightSource: [elements.feDistantLight, elements.fePointLight, elements.feSpotLight],
  neverRendered: [elements.clipPath, elements.defs, elements.linearGradient, elements.marker, elements.mask, elements.meshgradient, elements.metadata, elements.pattern, elements.radialGradient, elements.script, elements.style, elements.symbol, elements.title],
  paintServer: [elements.linearGradient, elements.meshgradient, elements.pattern, elements.radialGradient],
  renderable: [elements.a, elements.circle, elements.ellipse, elements.foreignObject, elements.g, elements.image, elements.line, elements.mesh, elements.path, elements.polygon, elements.polyline, elements.rect, elements.svg, elements.switch, elements.symbol, elements.text, elements.textPath, elements.tspan, elements.unknown, elements.use],
  shape: [elements.circle, elements.ellipse, elements.line, elements.mesh, elements.path, elements.polygon, elements.polyline, elements.rect],
  structural: [elements.defs, elements.g, elements.svg, elements.symbol, elements.use],
  textContent: [elements.textPath, elements.text, elements.tspan],
  textContentChild: [elements.textPath, elements.tspan],
  uncategorized: [elements.clipPath, elements.filter, elements.foreignObject, elements.meshpatch, elements.meshrow, elements.script, elements.style, elements.view]
}
